# Generated by Django 5.1.2 on 2024-10-23 19:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('azure', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='error',
            old_name='machine',
            new_name='machineID',
        ),
    ]
