# Generated by Django 5.1.2 on 2024-10-23 20:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('azure', '0002_rename_machine_error_machineid'),
    ]

    operations = [
        migrations.RenameField(
            model_name='error',
            old_name='machineID',
            new_name='machine',
        ),
    ]
